export {default as Error} from './Error'
export {default as MainMenu} from './MainMenu'
export {default as PageTemplate} from './PageTemplate'
export {default as AboutMenu} from './AboutMenu'
export {default as MainHeader} from './MainHeader'